Repository fireice-uk/xmr-stak, pull requests merged in 2018-08, with the labels that each got.

#1754 Grammar Fixes
  README.md
Labels: documentation

#1635 Docs - compilation RAM requirements
  doc/FAQ.md
  doc/compile_Linux.md
Labels: documentation

#1795 Incorrect Grammar fix
  xmrstak/donate-level.hpp
Labels: documentation

#1787 Download Link for AMD APP SDK 3.0 fixed
  doc/compile_Windows.md
Labels: bug, documentation

#1590 Add detail to CUDA detections, better for issue reports
  xmrstak/backend/nvidia/nvcc_code/cuda_extra.cu
Labels: backend nvidia, refactoring

#1807 add self test hashes
  xmrstak/backend/cpu/minethd.cpp
Labels: enhancement
