Repository fireice-uk/xmr-stak, pull requests merged in 2018-04, with the labels that each got.

#1267 Remove portbin from docs for now
  README.md
  doc/Linux_deployment.md
Labels: documentation

#1265 fix OpenCl AMD on OSX
  xmrstak/backend/amd/amd_gpu/opencl/cryptonight.cl
Labels: backend amd, bug

#1273 add stellite coin
  xmrstak/backend/amd/amd_gpu/gpu.cpp
  xmrstak/backend/amd/minethd.cpp
  xmrstak/backend/cpu/minethd.cpp
  xmrstak/backend/cpu/minethd.hpp
  xmrstak/backend/nvidia/minethd.cpp
  xmrstak/backend/nvidia/nvcc_code/cryptonight.hpp
  xmrstak/backend/nvidia/nvcc_code/cuda_core.cu
  xmrstak/backend/nvidia/nvcc_code/cuda_extra.cu
  xmrstak/jconf.cpp
  xmrstak/jconf.hpp
Labels: feature

#1299 fix cuda architecture detection
  xmrstak/backend/nvidia/nvcc_code/cuda_extra.cu
Labels: backend nvidia, bug

#1300 NVIDIA: fix sumokoin
  xmrstak/backend/nvidia/nvcc_code/cuda_core.cu
  xmrstak/version.cpp
Labels: backend nvidia, bug

#1327 Repair all 'namepsace' to 'namespace' (all within comments)
  xmrstak/backend/amd/autoAdjust.hpp
  xmrstak/backend/backendConnector.cpp
  xmrstak/backend/backendConnector.hpp
  xmrstak/backend/cpu/autoAdjust.hpp
  xmrstak/backend/cpu/autoAdjustHwloc.hpp
  xmrstak/backend/cpu/crypto/skein_port.h
  xmrstak/backend/cpu/jconf.cpp
  xmrstak/backend/cpu/jconf.hpp
  xmrstak/backend/cpu/minethd.cpp
  xmrstak/backend/cpu/minethd.hpp
  xmrstak/backend/globalStates.cpp
  xmrstak/backend/globalStates.hpp
  xmrstak/backend/iBackend.hpp
  xmrstak/backend/miner_work.hpp
  xmrstak/backend/nvidia/autoAdjust.hpp
  xmrstak/backend/nvidia/jconf.hpp
  xmrstak/backend/nvidia/minethd.hpp
  xmrstak/backend/nvidia/nvcc_code/cuda_extra.cu
  xmrstak/backend/plugin.hpp
  xmrstak/misc/configEditor.hpp
  xmrstak/misc/environment.hpp
  xmrstak/misc/executor.hpp
  xmrstak/misc/telemetry.cpp
  xmrstak/misc/telemetry.hpp
  xmrstak/misc/utility.cpp
  xmrstak/misc/utility.hpp
  xmrstak/net/msgstruct.hpp
  xmrstak/params.hpp
Labels: documentation

#1324 Fix spelling mistake in gpu.cpp
  xmrstak/backend/amd/amd_gpu/gpu.cpp
Labels: backend amd

#1372 amd simplify kernel for different algorithms
  xmrstak/backend/amd/amd_gpu/gpu.cpp
  xmrstak/backend/amd/amd_gpu/gpu.hpp
  xmrstak/backend/amd/amd_gpu/opencl/cryptonight.cl
  xmrstak/backend/amd/minethd.cpp
Labels: backend amd, refactoring

#1375 expose original algorithm
  xmrstak/jconf.cpp
  xmrstak/pools.tpl
Labels: enhancement

#1112 allow non AMD OpenCL driver and devices
  xmrstak/backend/amd/amd_gpu/gpu.cpp
  xmrstak/backend/amd/amd_gpu/gpu.hpp
  xmrstak/backend/amd/autoAdjust.hpp
  xmrstak/backend/amd/minethd.cpp
  xmrstak/backend/backendConnector.cpp
  xmrstak/cli/cli-miner.cpp
  xmrstak/params.hpp
Labels: backend nvidia, feature

#1437 fix wrong algo selection
  xmrstak/backend/amd/amd_gpu/gpu.cpp
  xmrstak/backend/amd/autoAdjust.hpp
  xmrstak/backend/amd/minethd.cpp
  xmrstak/backend/cpu/autoAdjust.hpp
  xmrstak/backend/cpu/autoAdjustHwloc.hpp
  xmrstak/backend/cpu/crypto/cryptonight_common.cpp
  xmrstak/backend/cpu/minethd.cpp
  xmrstak/backend/nvidia/minethd.cpp
  xmrstak/backend/nvidia/nvcc_code/cuda_extra.cu
  xmrstak/jconf.cpp
  xmrstak/jconf.hpp
  xmrstak/misc/coinDescription.hpp
  xmrstak/misc/executor.cpp
Labels: bug

#1449 fix wrong unique_lock usage
  xmrstak/net/jpsock.cpp
Labels: bug

#1451 Update ITNS with v4 fork to CN v1
  xmrstak/jconf.cpp
Labels: refactoring

#1448 CUDA 8 deprecation warning silencer
  CMakeLists.txt
Labels: backend nvidia

#1454 BBSCoin support and get ready for cryptonight v7 upgrade
  README.md
  xmrstak/jconf.cpp
  xmrstak/pools.tpl
Labels: enhancement

#1468 Fixes #1467
  xmrstak/backend/cpu/minethd.cpp
Labels: bug

#1469 Add turtlecoin as a config option
  README.md
  xmrstak/jconf.cpp
  xmrstak/pools.tpl
Labels: enhancement

#1489 add support for IPBC coin
  README.md
  xmrstak/backend/amd/amd_gpu/gpu.cpp
  xmrstak/backend/amd/amd_gpu/opencl/cryptonight.cl
  xmrstak/backend/cpu/crypto/cryptonight_aesni.h
  xmrstak/backend/cpu/minethd.cpp
  xmrstak/backend/cryptonight.hpp
  xmrstak/backend/nvidia/nvcc_code/cuda_core.cu
  xmrstak/jconf.cpp
  xmrstak/misc/executor.cpp
  xmrstak/net/jpsock.cpp
  xmrstak/pools.tpl
Labels: enhancement

#1486 fix that cli option `--noAMDCache`
  xmrstak/backend/amd/amd_gpu/gpu.cpp
Labels: backend amd, bug
