Repository fireice-uk/xmr-stak, pull requests merged in 2018-10, with the labels that each got.

#1857 add CUDA 10.0 support
  CMakeLists.txt
Labels: backend nvidia, enhancement

#1843 NVIDIA: sqrt optimization cryptonight_v8
  xmrstak/backend/nvidia/nvcc_code/cuda_fast_int_math_v2.hpp
Labels: refactoring

#1844 AMD: remove unused functions
  xmrstak/backend/amd/amd_gpu/gpu.cpp
  xmrstak/backend/amd/amd_gpu/opencl/fast_int_math_v2.cl
Labels: refactoring

#1850 cryptonight_v8 version 2
  xmrstak/backend/amd/amd_gpu/opencl/cryptonight.cl
  xmrstak/backend/cpu/autoAdjust.hpp
  xmrstak/backend/cpu/crypto/asm/cryptonight_v8_double_main_loop_sandybridge_linux.inc
  xmrstak/backend/cpu/crypto/asm/cryptonight_v8_double_main_loop_sandybridge_win64.inc
  xmrstak/backend/cpu/crypto/asm/cryptonight_v8_main_loop.S
  xmrstak/backend/cpu/crypto/asm/cryptonight_v8_main_loop.asm
  xmrstak/backend/cpu/crypto/asm/cryptonight_v8_main_loop_ivybridge_linux.inc
  xmrstak/backend/cpu/crypto/asm/cryptonight_v8_main_loop_ivybridge_win64.inc
  xmrstak/backend/cpu/crypto/asm/cryptonight_v8_main_loop_ryzen_linux.inc
  xmrstak/backend/cpu/crypto/asm/cryptonight_v8_main_loop_ryzen_win64.inc
  xmrstak/backend/cpu/crypto/cryptonight_aesni.h
  xmrstak/backend/cpu/minethd.cpp
  xmrstak/backend/nvidia/minethd.cpp
  xmrstak/backend/nvidia/nvcc_code/cuda_core.cu
  xmrstak/backend/nvidia/nvcc_code/cuda_extra.cu
Labels: enhancement

#1862 add cpu family and model detection
  xmrstak/backend/cpu/autoAdjust.hpp
  xmrstak/backend/cpu/autoAdjustHwloc.hpp
  xmrstak/backend/cpu/config.tpl
  xmrstak/backend/cpu/cpuType.cpp
  xmrstak/backend/cpu/cpuType.hpp
  xmrstak/backend/cpu/minethd.cpp
Labels: enhancement, refactoring

#1859 rework all currencies
  doc/FAQ.md
  xmrstak/backend/amd/config.tpl
  xmrstak/jconf.cpp
  xmrstak/pools.tpl
Labels: refactoring

#1864 fix wrong option in config.tpl
  xmrstak/config.tpl
Labels: bug

#1865 CUDA: tine cryptonight_v8
  xmrstak/backend/nvidia/nvcc_code/cuda_core.cu
  xmrstak/backend/nvidia/nvcc_code/cuda_extra.cu
Labels: backend nvidia, refactoring

#1866 fix invalid shares
  xmrstak/backend/amd/amd_gpu/opencl/cryptonight.cl
Labels: backend amd, bug

#1872 CPU: fix logical error
  xmrstak/backend/cpu/minethd.cpp
Labels: backend cpu, bug

#1876 compatibility and better messages
  CMakeLists.txt
  xmrstak/backend/amd/minethd.cpp
  xmrstak/backend/cpu/crypto/cryptonight_common.cpp
  xmrstak/backend/cpu/minethd.cpp
  xmrstak/cli/cli-miner.cpp
  xmrstak/config.tpl
Labels: refactoring

#1877 CUDA: use volatile pointer
  xmrstak/backend/nvidia/nvcc_code/cuda_core.cu
Labels: backend nvidia, refactoring

#1878 CUDA: select hash function from array
  xmrstak/backend/nvidia/autoAdjust.hpp
  xmrstak/backend/nvidia/config.tpl
  xmrstak/backend/nvidia/jconf.cpp
  xmrstak/backend/nvidia/jconf.hpp
  xmrstak/backend/nvidia/minethd.cpp
  xmrstak/backend/nvidia/nvcc_code/cryptonight.hpp
  xmrstak/backend/nvidia/nvcc_code/cuda_core.cu
  xmrstak/backend/nvidia/nvcc_code/cuda_extra.cu
Labels: backend nvidia, refactoring

#1887 CUDA: fix invalid results
  xmrstak/backend/nvidia/autoAdjust.hpp
  xmrstak/backend/nvidia/config.tpl
  xmrstak/backend/nvidia/nvcc_code/cuda_core.cu
Labels: backend nvidia, bug

#1889 fix right bitshift in `amd_bitalign`
  xmrstak/backend/amd/amd_gpu/opencl/cryptonight.cl
Labels: backend amd, bug

#1891 NVIDIA: rename config option `comp_mode`
  xmrstak/backend/nvidia/autoAdjust.hpp
  xmrstak/backend/nvidia/config.tpl
  xmrstak/backend/nvidia/jconf.cpp
  xmrstak/backend/nvidia/jconf.hpp
  xmrstak/backend/nvidia/minethd.cpp
  xmrstak/backend/nvidia/nvcc_code/cryptonight.hpp
  xmrstak/backend/nvidia/nvcc_code/cuda_core.cu
Labels: backend nvidia, refactoring

#1895 NVIDIA: tweak `get_reciprocal`
  xmrstak/backend/nvidia/nvcc_code/cuda_core.cu
  xmrstak/backend/nvidia/nvcc_code/cuda_fast_int_math_v2.hpp
Labels: backend nvidia, refactoring

#1896 update documantion
  doc/tuning.md
  doc/usage.md
Labels: documentation

#1898 NVIDIA: support for multiple CUDA libs
  xmrstak/backend/backendConnector.cpp
  xmrstak/backend/nvidia/minethd.cpp
  xmrstak/backend/plugin.hpp
Labels: backend nvidia, feature

#1940 reduce blocking during metric update
  xmrstak/misc/telemetry.cpp
  xmrstak/misc/telemetry.hpp
Labels: refactoring

#1951 fix AMD driver 14
  xmrstak/backend/amd/amd_gpu/opencl/fast_int_math_v2.cl
Labels: backend amd, bug

#1954 update AMD install docu
  doc/compile_Linux.md
  doc/compile_Windows.md
Labels: documentation

#1950 Remove dead code
  xmrstak/backend/amd/amd_gpu/gpu.cpp
Labels: refactoring

#1949 Add missing test for cryptonight_lite
  xmrstak/backend/cpu/minethd.cpp
Labels: bug

#1956 Add console warning on GPU error.
  xmrstak/misc/executor.cpp
Labels: feature

#2001 Update for upcoming Graft CNv2 fork
  xmrstak/jconf.cpp
Labels: currency

#2003 NVIDIA: fix wrong number of threads
  xmrstak/backend/nvidia/nvcc_code/cuda_core.cu
Labels: backend nvidia, bug
