Repository fireice-uk/xmr-stak, pull requests merged in 2018-07, with the labels that each got.

#1664 Fixed fork version for currency 'electroneum'
  xmrstak/jconf.cpp
Labels: bug

#1702 optimize cn-heavy AMD
  xmrstak/backend/amd/amd_gpu/opencl/cryptonight.cl
Labels: backend amd

#1703 add ryo currency
  README.md
  xmrstak/jconf.cpp
  xmrstak/pools.tpl
Labels: feature

#1704 remove cryptonight coins
  README.md
  xmrstak/jconf.cpp
  xmrstak/pools.tpl
Labels: documentation

#1710 fix wrong miner algorithm in result data
  xmrstak/backend/amd/minethd.cpp
  xmrstak/backend/cpu/minethd.cpp
  xmrstak/backend/nvidia/minethd.cpp
  xmrstak/misc/executor.cpp
  xmrstak/net/msgstruct.hpp
Labels: bug

#1660 Grammar fixes; mmap alloc failed error remark for Arch Linux.
  doc/FAQ.md
  doc/compile.md
  scripts/build_xmr-stak_docker/build_xmr-stak_docker.sh
Labels: documentation

#1717 cryptonight_bittube2
  README.md
  xmrstak/backend/amd/amd_gpu/gpu.cpp
  xmrstak/backend/amd/amd_gpu/opencl/cryptonight.cl
  xmrstak/backend/amd/amd_gpu/opencl/wolf-aes.cl
  xmrstak/backend/cpu/crypto/cryptonight_aesni.h
  xmrstak/backend/cpu/minethd.cpp
  xmrstak/backend/cryptonight.hpp
  xmrstak/backend/nvidia/nvcc_code/cuda_core.cu
  xmrstak/backend/nvidia/nvcc_code/cuda_extra.cu
  xmrstak/jconf.cpp
  xmrstak/pools.tpl
Labels: feature

#1722 fix broken OpenCL 1.2 support
  xmrstak/backend/amd/amd_gpu/opencl/wolf-aes.cl
Labels: backend amd, bug

#1726 release 2.4.7
  xmrstak/backend/amd/amd_gpu/opencl/wolf-aes.cl
  xmrstak/version.cpp
Labels: backend amd, bug

#1746 Fix Spelling
  README.md
Labels: documentation

#1735 adding qrl as a config option
  README.md
  xmrstak/jconf.cpp
  xmrstak/pools.tpl
Labels: enhancement
