Repository fireice-uk/xmr-stak, pull requests merged in 2019-12, with the labels that each got.

#2596 [RX] optimize randomX
  xmrstak/backend/cpu/crypto/randomx/aes_hash.cpp
  xmrstak/backend/cpu/crypto/randomx/aes_hash.hpp
  xmrstak/backend/cpu/crypto/randomx/intrin_portable.h
  xmrstak/backend/cpu/crypto/randomx/jit_compiler.hpp
  xmrstak/backend/cpu/crypto/randomx/jit_compiler_x86.cpp
  xmrstak/backend/cpu/crypto/randomx/jit_compiler_x86.hpp
  xmrstak/backend/cpu/crypto/randomx/randomx.cpp
  xmrstak/backend/cpu/crypto/randomx/randomx.h
  xmrstak/backend/cpu/crypto/randomx/virtual_machine.cpp
  xmrstak/backend/cpu/crypto/randomx/virtual_machine.hpp
  xmrstak/backend/cpu/minethd.cpp
Labels: backend cpu, randomX

#2590 [RX] fix memory pinning
  xmrstak/backend/cpu/minethd.cpp
Labels: backend cpu, bug, randomX

#2591 [RX] CPU: remove unused params
  xmrstak/backend/cpu/autoAdjust.hpp
  xmrstak/backend/cpu/autoAdjustHwloc.hpp
Labels: backend cpu, randomX

#2599 optimize hash rate
  xmrstak/backend/cpu/minethd.cpp
Labels: enhancement, randomX

#2603 fix broken link
  doc/README.md
Labels: bug, documentation

#2604 backport fix broken link
  doc/README.md
Labels: bug

#2607 [RX] add link to youtube
  doc/README.md
Labels: documentation, randomX

#2608 add youtube link
  doc/README.md
Labels: documentation

#2609 [RX] disable dev support cli option
  xmrstak/cli/cli-miner.cpp
  xmrstak/misc/executor.cpp
  xmrstak/params.hpp
Labels: enhancement, randomX

#2610 link update for the release
  doc/README.md
Labels: documentation

#2611 [RX] additional changes for the release
  doc/README.md
  xmrstak/cli/cli-miner.cpp
  xmrstak/misc/executor.cpp
  xmrstak/params.hpp
Labels: documentation, randomX

#2622 [RX] add ocl-icd-opencl-dev depentancy
  doc/compile/compile_Linux.md
Labels: currency, randomX

#2621 [RX] fix multihash
  xmrstak/backend/cpu/crypto/cryptonight_aesni.h
Labels: backend cpu, bug, randomX

#2623 [RX] optimize hash calculation up to 5%
  xmrstak/backend/cpu/minethd.cpp
Labels: enhancement, randomX

#2624 [RX] fix windows huge page support
  xmrstak/backend/cpu/minethd.cpp
  xmrstak/cli/cli-miner.cpp
Labels: backend cpu, bug, randomX

#2625 [RX] update travis tests
  .travis.yml
Labels: refactoring

#2626 update travis
  .travis.yml
  CMakeLists.txt
Labels: refactoring

#2628 add arqma support
  xmrstak/backend/amd/amd_gpu/gpu.cpp
  xmrstak/backend/amd/amd_gpu/opencl/RandomX/randomx_constants_arqma.h
  xmrstak/backend/cpu/crypto/cryptonight_aesni.h
  xmrstak/backend/cpu/minethd.cpp
  xmrstak/backend/cryptonight.hpp
  xmrstak/backend/nvidia/RandomX_Arqma/configuration.h
  xmrstak/backend/nvidia/RandomX_Arqma/randomx_arqma.cu
  xmrstak/backend/nvidia/minethd.cpp
  xmrstak/backend/nvidia/nvcc_code/cryptonight.hpp
  xmrstak/jconf.cpp
  xmrstak/pools.tpl
Labels: backend amd, backend cpu, backend nvidia, currency

#2627 Linux 1GiB page support
  doc/tuning.md
  xmrstak/backend/cpu/crypto/common/VirtualMemory.h
  xmrstak/backend/cpu/crypto/common/VirtualMemory_unix.cpp
  xmrstak/backend/cpu/crypto/common/VirtualMemory_win.cpp
  xmrstak/backend/cpu/crypto/cryptonight.h
  xmrstak/backend/cpu/crypto/randomx/allocator.cpp
  xmrstak/backend/cpu/crypto/randomx/allocator.hpp
  xmrstak/backend/cpu/crypto/randomx/randomx.cpp
  xmrstak/backend/cpu/crypto/randomx/randomx.h
  xmrstak/backend/cpu/crypto/randomx/virtual_memory.cpp
  xmrstak/backend/cpu/crypto/randomx/virtual_memory.hpp
Labels: backend cpu, enhancement

#2630 [RX] fix outdated documentation
  CMakeLists.txt
  doc/README.md
  doc/compile/compile_Linux.md
  doc/compile/compile_Windows.md
  doc/compile/compile_macOS.md
  doc/troubleshooting.md
  doc/usage.md
  scripts/build_xmr-stak_docker/build_xmr-stak_docker.sh
Labels: documentation

#2631 [RX] version update to 1.0.3-rx
  xmrstak/version.cpp
Labels: documentation

#2632 add arqma to readme
  doc/README.md
Labels: documentation

#2633 [RX] release 1.0.3-rx
  .travis.yml
  CMakeLists.txt
  doc/README.md
  doc/compile/compile_Linux.md
  doc/compile/compile_Windows.md
  doc/compile/compile_macOS.md
  doc/troubleshooting.md
  doc/tuning.md
  doc/usage.md
  scripts/build_xmr-stak_docker/build_xmr-stak_docker.sh
  xmrstak/backend/amd/amd_gpu/gpu.cpp
  xmrstak/backend/amd/amd_gpu/opencl/RandomX/randomx_constants_arqma.h
  xmrstak/backend/cpu/crypto/common/VirtualMemory.h
  xmrstak/backend/cpu/crypto/common/VirtualMemory_unix.cpp
  xmrstak/backend/cpu/crypto/common/VirtualMemory_win.cpp
  xmrstak/backend/cpu/crypto/cryptonight.h
  xmrstak/backend/cpu/crypto/cryptonight_aesni.h
  xmrstak/backend/cpu/crypto/randomx/allocator.cpp
  xmrstak/backend/cpu/crypto/randomx/allocator.hpp
  xmrstak/backend/cpu/crypto/randomx/randomx.cpp
  xmrstak/backend/cpu/crypto/randomx/randomx.h
  xmrstak/backend/cpu/crypto/randomx/virtual_memory.cpp
  xmrstak/backend/cpu/crypto/randomx/virtual_memory.hpp
  xmrstak/backend/cpu/minethd.cpp
  xmrstak/backend/cryptonight.hpp
  xmrstak/backend/nvidia/RandomX_Arqma/configuration.h
  xmrstak/backend/nvidia/RandomX_Arqma/randomx_arqma.cu
  xmrstak/backend/nvidia/minethd.cpp
  xmrstak/backend/nvidia/nvcc_code/cryptonight.hpp
  xmrstak/cli/cli-miner.cpp
  xmrstak/jconf.cpp
  xmrstak/pools.tpl
  xmrstak/version.cpp
Labels: documentation, randomX

#2635 [RX] CPU: numa support/better autoconfig
  xmrstak/backend/amd/amd_gpu/gpu.cpp
  xmrstak/backend/amd/autoAdjust.hpp
  xmrstak/backend/amd/minethd.cpp
  xmrstak/backend/cpu/autoAdjust.hpp
  xmrstak/backend/cpu/autoAdjustHwloc.hpp
  xmrstak/backend/cpu/crypto/common/VirtualMemory_unix.cpp
  xmrstak/backend/cpu/crypto/cryptonight.h
  xmrstak/backend/cpu/crypto/cryptonight_1.cpp
  xmrstak/backend/cpu/crypto/cryptonight_1.h
  xmrstak/backend/cpu/crypto/cryptonight_aesni.h
  xmrstak/backend/cpu/crypto/cryptonight_common.cpp
  xmrstak/backend/cpu/hwlocHelper.cpp
  xmrstak/backend/cpu/hwlocHelper.hpp
  xmrstak/backend/cpu/hwlocMemory.cpp
  xmrstak/backend/cpu/hwlocMemory.hpp
  xmrstak/backend/cpu/minethd.cpp
  xmrstak/backend/cryptonight.hpp
  xmrstak/backend/nvidia/RandomX/randomx.cu
  xmrstak/backend/nvidia/minethd.cpp
  xmrstak/backend/nvidia/nvcc_code/cuda_extra.cu
  xmrstak/net/jpsock.cpp
Labels: backend cpu, feature, randomX

#2637 [RX] randomx linux booster script
  CMakeLists.txt
  doc/tuning.md
  scripts/randomx_booster.sh
Labels: backend cpu, feature, randomX

#2638 [RX] add warning for MSR changes
  scripts/randomx_booster.sh
Labels: backend cpu, bug, randomX

#2644 [RX] Implement Ryzen speedups
  xmrstak/backend/cpu/crypto/randomx/asm/program_read_dataset_ryzen.inc
  xmrstak/backend/cpu/crypto/randomx/jit_compiler_x86.cpp
  xmrstak/backend/cpu/crypto/randomx/jit_compiler_x86.hpp
  xmrstak/backend/cpu/crypto/randomx/jit_compiler_x86_static.S
  xmrstak/backend/cpu/crypto/randomx/jit_compiler_x86_static.asm
  xmrstak/backend/cpu/crypto/randomx/jit_compiler_x86_static.hpp
  xmrstak/backend/cpu/crypto/randomx/randomx.cpp
  xmrstak/backend/cpu/crypto/randomx/randomx.h
Labels: randomX

#2646 [rx] increase version
  xmrstak/version.cpp
Labels: randomX

#2647 [RX] release 1.0.4
  CMakeLists.txt
  doc/tuning.md
  scripts/randomx_booster.sh
  xmrstak/backend/amd/amd_gpu/gpu.cpp
  xmrstak/backend/amd/autoAdjust.hpp
  xmrstak/backend/amd/minethd.cpp
  xmrstak/backend/cpu/autoAdjust.hpp
  xmrstak/backend/cpu/autoAdjustHwloc.hpp
  xmrstak/backend/cpu/crypto/common/VirtualMemory_unix.cpp
  xmrstak/backend/cpu/crypto/cryptonight.h
  xmrstak/backend/cpu/crypto/cryptonight_1.cpp
  xmrstak/backend/cpu/crypto/cryptonight_1.h
  xmrstak/backend/cpu/crypto/cryptonight_aesni.h
  xmrstak/backend/cpu/crypto/cryptonight_common.cpp
  xmrstak/backend/cpu/crypto/randomx/asm/program_read_dataset_ryzen.inc
  xmrstak/backend/cpu/crypto/randomx/jit_compiler_x86.cpp
  xmrstak/backend/cpu/crypto/randomx/jit_compiler_x86.hpp
  xmrstak/backend/cpu/crypto/randomx/jit_compiler_x86_static.S
  xmrstak/backend/cpu/crypto/randomx/jit_compiler_x86_static.asm
  xmrstak/backend/cpu/crypto/randomx/jit_compiler_x86_static.hpp
  xmrstak/backend/cpu/crypto/randomx/randomx.cpp
  xmrstak/backend/cpu/crypto/randomx/randomx.h
  xmrstak/backend/cpu/hwlocHelper.cpp
  xmrstak/backend/cpu/hwlocHelper.hpp
  xmrstak/backend/cpu/hwlocMemory.cpp
  xmrstak/backend/cpu/hwlocMemory.hpp
  xmrstak/backend/cpu/minethd.cpp
  xmrstak/backend/cryptonight.hpp
  xmrstak/backend/nvidia/RandomX/randomx.cu
  xmrstak/backend/nvidia/minethd.cpp
  xmrstak/backend/nvidia/nvcc_code/cuda_extra.cu
  xmrstak/misc/win_msr.cpp
  xmrstak/misc/win_msr.hpp
  xmrstak/net/jpsock.cpp
  xmrstak/version.cpp
Labels: randomX

#2648 update RX5XXX auto cfg
  xmrstak/backend/amd/autoAdjust.hpp
Labels: bug, enhancement
