Repository fireice-uk/xmr-stak, pull requests merged in 2019-11, with the labels that each got.

#2551 Correct authors of RandomX mining code
  xmrstak/cli/cli-miner.cpp
Labels: documentation

#2553 [RX] fix CI
  .appveyor.yml
  .travis.yml
Labels: bug

#2537 remove aeon support
  README.md
  xmrstak/jconf.cpp
Labels: currency

#2568 fix travis
  .travis.yml
Labels: bug, randomX

#2554 [RX] add currency names
  xmrstak/jconf.cpp
  xmrstak/pools.tpl
Labels: enhancement

#2555 [RX] advertise for disabling self test
  xmrstak/backend/cpu/minethd.cpp
Labels: enhancement

#2556 [RX] fix hwloc warning
  xmrstak/backend/cpu/hwlocMemory.cpp
Labels: randomX, warning

#2558 [RX] fix irgnored tls on first start
  xmrstak/cli/cli-miner.cpp
  xmrstak/misc/executor.cpp
Labels: bug, randomX

#2561 [RX] fix miner benchmark mode
  xmrstak/backend/cpu/crypto/cryptonight_aesni.h
  xmrstak/backend/cpu/minethd.cpp
  xmrstak/backend/cpu/minethd.hpp
  xmrstak/cli/cli-miner.cpp
  xmrstak/net/socket.cpp
Labels: bug, randomX

#2567 [RX] NVIDIA: fix auto adjustment
  xmrstak/backend/nvidia/nvcc_code/cuda_extra.cu
Labels: backend nvidia, bug, randomX

#2569 [RX] version increase to 1.0.1-rx
  xmrstak/version.cpp
Labels: documentation, randomX

#2538 [NVIDIA] fix possible out of memory with auto cfg
  xmrstak/backend/nvidia/nvcc_code/cuda_extra.cu
Labels: backend nvidia, bug

#2557 fix hwloc warning
  xmrstak/backend/cpu/hwlocMemory.cpp
Labels: warning

#2559 fix tsl not used on first start
  xmrstak/cli/cli-miner.cpp
  xmrstak/misc/executor.cpp
Labels: bug

#2562 fix benchmark mode
  xmrstak/cli/cli-miner.cpp
Labels: bug

#2570 xmr-stak-rx 1.0.1 release
  .appveyor.yml
  .travis.yml
  xmrstak/backend/cpu/crypto/cryptonight_aesni.h
  xmrstak/backend/cpu/hwlocMemory.cpp
  xmrstak/backend/cpu/minethd.cpp
  xmrstak/backend/cpu/minethd.hpp
  xmrstak/backend/nvidia/nvcc_code/cuda_extra.cu
  xmrstak/cli/cli-miner.cpp
  xmrstak/jconf.cpp
  xmrstak/misc/executor.cpp
  xmrstak/net/socket.cpp
  xmrstak/pools.tpl
  xmrstak/version.cpp
Labels: documentation, randomX

#2573 [RX] rename shared libraries
  CMakeLists.txt
  xmrstak/backend/backendConnector.cpp
Labels: backend amd, backend nvidia, bug, randomX

#2574 version increase to 1.0.2-rx
  xmrstak/version.cpp
Labels: randomX

#2578 [RX] update README
  README.md
  doc/README.md
  doc/_img/2ragerx-btn.png
  doc/_img/2xmr-stak-btn.png
  doc/_img/YT.png
  doc/_img/cpu.png
  doc/_img/faq-green.png
  doc/_img/faq.png
  doc/_img/features-xmr-stak.png
  doc/_img/features.png
  doc/_img/fee.png
  doc/_img/fine-tuning-green.png
  doc/_img/fine-tuning.png
  doc/_img/gpu.png
  doc/_img/header.png
  doc/_img/how-to-compile-green.png
  doc/_img/how-to-compile.png
  doc/_img/html_reports.png
  doc/_img/menu-donations-green.png
  doc/_img/menu-donations.png
  doc/_img/menu-features-green.png
  doc/_img/menu-features.png
  doc/_img/menu-get-miner-green.png
  doc/_img/menu-get-miner.png
  doc/_img/menu-support-green.png
  doc/_img/menu-support.png
  doc/_img/menu-supported-coins-green.png
  doc/_img/menu-supported-coins.png
  doc/_img/ragerx-btn.png
  doc/_img/ragerx.png
  doc/_img/rx.png
  doc/_img/split.png
  doc/_img/troubleshooting-green.png
  doc/_img/troubleshooting.png
  doc/_img/usage-green.png
  doc/_img/usage.png
  doc/_img/xmr-stak-btn-active.png
  doc/_img/xmr-stak-btn.png
  doc/_img/xmr-stak-cpu-connection.png
  doc/_img/xmr-stak-cpu-hashrate.png
  doc/_img/xmr-stak-cpu-results.png
  doc/_img/xmr-stak-rx-btn-inactive.png
  doc/_img/xmr-stak-rx-btn.png
  doc/_img/xmrig.png
Labels: documentation, randomX

#2579 update README
  README.md
  doc/README.md
  doc/_img/2ragerx-btn.png
  doc/_img/2xmr-stak-btn.png
  doc/_img/YT.png
  doc/_img/cpu.png
  doc/_img/faq-green.png
  doc/_img/faq.png
  doc/_img/features-xmr-stak.png
  doc/_img/features.png
  doc/_img/fee.png
  doc/_img/fine-tuning-green.png
  doc/_img/fine-tuning.png
  doc/_img/gpu.png
  doc/_img/header.png
  doc/_img/how-to-compile-green.png
  doc/_img/how-to-compile.png
  doc/_img/html_reports.png
  doc/_img/menu-donations-green.png
  doc/_img/menu-donations.png
  doc/_img/menu-features-green.png
  doc/_img/menu-features.png
  doc/_img/menu-get-miner-green.png
  doc/_img/menu-get-miner.png
  doc/_img/menu-support-green.png
  doc/_img/menu-support.png
  doc/_img/menu-supported-coins-green.png
  doc/_img/menu-supported-coins.png
  doc/_img/ragerx-btn.png
  doc/_img/ragerx.png
  doc/_img/rx.png
  doc/_img/split.png
  doc/_img/troubleshooting-green.png
  doc/_img/troubleshooting.png
  doc/_img/usage-green.png
  doc/_img/usage.png
  doc/_img/xmr-stak-btn-active.png
  doc/_img/xmr-stak-btn.png
  doc/_img/xmr-stak-cpu-connection.png
  doc/_img/xmr-stak-cpu-hashrate.png
  doc/_img/xmr-stak-cpu-results.png
  doc/_img/xmr-stak-rx-btn-inactive.png
  doc/_img/xmr-stak-rx-btn.png
  doc/_img/xmrig.png
Labels: documentation

#2580 version increase to 2.10.8
  xmrstak/version.cpp
Labels: documentation

#2581 remove monero support
  xmrstak/jconf.cpp
  xmrstak/pools.tpl
Labels: currency, documentation

#2585 [RX] fix documentation
  doc/FAQ.md
  doc/compile/compile.md
  doc/compile/compile_FreeBSD.md
  doc/compile/compile_Linux.md
  doc/compile/compile_macOS.md
  doc/troubleshooting.md
  doc/tuning.md
  doc/usage.md
Labels: bug, documentation, randomX
