Repository fireice-uk/xmr-stak, pull requests merged in 2019-05, with the labels that each got.

#2419 change lethean POW to cn_r
  xmrstak/jconf.cpp
Labels: bug, currency

#2420 change xmr pool suggestion
  xmrstak/jconf.cpp
Labels: documentation

#2423 rename intense to lethean
  xmrstak/pools.tpl
Labels: bug, currency, documentation

#2425 remove freehaven support
  xmrstak/jconf.cpp
  xmrstak/pools.tpl
Labels: currency

#2426 change stellite to torque
  README.md
  xmrstak/jconf.cpp
  xmrstak/pools.tpl
Labels: currency, documentation

#2430 Fallback from hwloc autoconf to basic autoconf
  xmrstak/backend/cpu/autoAdjustHwloc.hpp
  xmrstak/backend/cpu/minethd.cpp
Labels: enhancement

#2431 --h-print-time CLI option
  xmrstak/cli/cli-miner.cpp
  xmrstak/config.tpl
  xmrstak/jconf.cpp
  xmrstak/params.hpp
Labels: enhancement

#2442 Print responsible GPU and pool for accepted/rejected shares
  xmrstak/backend/amd/minethd.cpp
  xmrstak/backend/iBackend.hpp
  xmrstak/backend/nvidia/minethd.cpp
  xmrstak/misc/executor.cpp
Labels: feature
