Repository fireice-uk/xmr-stak, pull requests merged in 2019-03, with the labels that each got.

#2247 log level 4 as default
  xmrstak/config.tpl
Labels: refactoring

#2268 cryptonight_r
  .appveyor.yml
  CMakeLists.txt
  xmrstak/backend/amd/OclCryptonightR_gen.cpp
  xmrstak/backend/amd/OclCryptonightR_gen.hpp
  xmrstak/backend/amd/amd_gpu/gpu.cpp
  xmrstak/backend/amd/amd_gpu/gpu.hpp
  xmrstak/backend/amd/amd_gpu/opencl/cryptonight_r.cl
  xmrstak/backend/amd/autoAdjust.hpp
  xmrstak/backend/amd/minethd.cpp
  xmrstak/backend/cpu/crypto/cryptonight.h
  xmrstak/backend/cpu/crypto/cryptonight_aesni.h
  xmrstak/backend/cpu/crypto/variant4_random_math.h
  xmrstak/backend/cpu/minethd.cpp
  xmrstak/backend/cpu/minethd.hpp
  xmrstak/backend/cryptonight.hpp
  xmrstak/backend/globalStates.cpp
  xmrstak/backend/globalStates.hpp
  xmrstak/backend/miner_work.hpp
  xmrstak/backend/nvidia/CudaCryptonightR_gen.cpp
  xmrstak/backend/nvidia/CudaCryptonightR_gen.hpp
  xmrstak/backend/nvidia/minethd.cpp
  xmrstak/backend/nvidia/nvcc_code/cryptonight.hpp
  xmrstak/backend/nvidia/nvcc_code/cuda_core.cu
  xmrstak/backend/nvidia/nvcc_code/cuda_cryptonight_r.curt
  xmrstak/backend/nvidia/nvcc_code/cuda_device.hpp
  xmrstak/backend/nvidia/nvcc_code/cuda_extra.cu
  xmrstak/cli/cli-miner.cpp
  xmrstak/config.tpl
  xmrstak/jconf.cpp
  xmrstak/misc/console.hpp
  xmrstak/misc/executor.cpp
  xmrstak/misc/jext.hpp
  xmrstak/net/jpsock.cpp
  xmrstak/net/jpsock.hpp
  xmrstak/net/msgstruct.hpp
Labels: backend amd, backend cpu, backend nvidia, currency

#2267 update version to 2.9.0
  xmrstak/version.cpp
Labels: documentation

#2269 release 2.9.0
  .appveyor.yml
  CMakeLists.txt
  xmrstak/backend/amd/OclCryptonightR_gen.cpp
  xmrstak/backend/amd/OclCryptonightR_gen.hpp
  xmrstak/backend/amd/amd_gpu/gpu.cpp
  xmrstak/backend/amd/amd_gpu/gpu.hpp
  xmrstak/backend/amd/amd_gpu/opencl/cryptonight_r.cl
  xmrstak/backend/amd/autoAdjust.hpp
  xmrstak/backend/amd/minethd.cpp
  xmrstak/backend/cpu/crypto/cryptonight.h
  xmrstak/backend/cpu/crypto/cryptonight_aesni.h
  xmrstak/backend/cpu/crypto/variant4_random_math.h
  xmrstak/backend/cpu/minethd.cpp
  xmrstak/backend/cpu/minethd.hpp
  xmrstak/backend/cryptonight.hpp
  xmrstak/backend/globalStates.cpp
  xmrstak/backend/globalStates.hpp
  xmrstak/backend/miner_work.hpp
  xmrstak/backend/nvidia/CudaCryptonightR_gen.cpp
  xmrstak/backend/nvidia/CudaCryptonightR_gen.hpp
  xmrstak/backend/nvidia/minethd.cpp
  xmrstak/backend/nvidia/nvcc_code/cryptonight.hpp
  xmrstak/backend/nvidia/nvcc_code/cuda_core.cu
  xmrstak/backend/nvidia/nvcc_code/cuda_cryptonight_r.curt
  xmrstak/backend/nvidia/nvcc_code/cuda_device.hpp
  xmrstak/backend/nvidia/nvcc_code/cuda_extra.cu
  xmrstak/cli/cli-miner.cpp
  xmrstak/config.tpl
  xmrstak/jconf.cpp
  xmrstak/misc/console.hpp
  xmrstak/misc/executor.cpp
  xmrstak/misc/jext.hpp
  xmrstak/net/jpsock.cpp
  xmrstak/net/jpsock.hpp
  xmrstak/net/msgstruct.hpp
  xmrstak/version.cpp
Labels: currency, documentation, feature

#2273 OpenCl: fix multi gpu support
  xmrstak/backend/amd/amd_gpu/gpu.cpp
Labels: backend amd, bug

#2280 fix wrong logic operator usage
  xmrstak/backend/cpu/crypto/cryptonight_aesni.h
Labels: backend cpu, bug

#2279 assembly patching
  CMakeLists.txt
  xmrstak/backend/amd/OclCryptonightR_gen.cpp
  xmrstak/backend/amd/minethd.cpp
  xmrstak/backend/cpu/crypto/CryptonightR_gen.cpp
  xmrstak/backend/cpu/crypto/asm/cnR/CryptonightR_template.S
  xmrstak/backend/cpu/crypto/asm/cnR/CryptonightR_template.asm
  xmrstak/backend/cpu/crypto/asm/cnR/CryptonightR_template.h
  xmrstak/backend/cpu/crypto/asm/cnR/CryptonightR_template.inc
  xmrstak/backend/cpu/crypto/asm/cnR/CryptonightR_template_win.inc
  xmrstak/backend/cpu/crypto/asm/cnR/CryptonightWOW_template.inc
  xmrstak/backend/cpu/crypto/asm/cnR/CryptonightWOW_template_win.inc
  xmrstak/backend/cpu/crypto/asm/cryptonight_v8_double_main_loop_sandybridge_linux.inc
  xmrstak/backend/cpu/crypto/asm/cryptonight_v8_double_main_loop_sandybridge_win64.inc
  xmrstak/backend/cpu/crypto/asm/cryptonight_v8_main_loop.S
  xmrstak/backend/cpu/crypto/asm/cryptonight_v8_main_loop.asm
  xmrstak/backend/cpu/crypto/asm/cryptonight_v8_main_loop_ivybridge_linux.inc
  xmrstak/backend/cpu/crypto/asm/cryptonight_v8_main_loop_ivybridge_win64.inc
  xmrstak/backend/cpu/crypto/asm/cryptonight_v8_main_loop_ryzen_linux.inc
  xmrstak/backend/cpu/crypto/asm/cryptonight_v8_main_loop_ryzen_win64.inc
  xmrstak/backend/cpu/crypto/cryptonight.h
  xmrstak/backend/cpu/crypto/cryptonight_aesni.h
  xmrstak/backend/cpu/crypto/variant4_random_math.h
  xmrstak/backend/cpu/minethd.cpp
  xmrstak/backend/cpu/minethd.hpp
  xmrstak/backend/cryptonight.hpp
  xmrstak/backend/nvidia/minethd.cpp
  xmrstak/backend/nvidia/nvcc_code/cryptonight.hpp
  xmrstak/backend/nvidia/nvcc_code/cuda_extra.cu
Labels: backend amd, backend cpu, backend nvidia, currency

#2274 CN_GPU: Fix old compilers and old kernels (Clang 3.5 tested, without CONFIG_HUGETLBFS)
  xmrstak/backend/cpu/crypto/cn_gpu_avx.cpp
  xmrstak/backend/cpu/crypto/cryptonight_common.cpp
Labels: enhancement

#2282 Support of CryptoNight v8 ReverseWaltz
  README.md
  xmrstak/backend/amd/amd_gpu/gpu.cpp
  xmrstak/backend/amd/amd_gpu/opencl/cryptonight.cl
  xmrstak/backend/amd/amd_gpu/opencl/fast_int_math_v2.cl
  xmrstak/backend/cpu/crypto/cryptonight_aesni.h
  xmrstak/backend/cpu/minethd.cpp
  xmrstak/backend/cpu/minethd.hpp
  xmrstak/backend/cryptonight.hpp
  xmrstak/backend/nvidia/nvcc_code/cuda_core.cu
  xmrstak/backend/nvidia/nvcc_code/cuda_extra.cu
  xmrstak/jconf.cpp
  xmrstak/pools.tpl
Labels: currency

#2251 Edited comments in configs, set default verbose to 4
  xmrstak/backend/amd/config.tpl
  xmrstak/pools.tpl
Labels: documentation

#2284 dev pool change
  xmrstak/misc/executor.cpp
Labels: refactoring

#2283 increase version to 2.10.0
  xmrstak/version.cpp
Labels: documentation

#2285 release 2.10.0
  CMakeLists.txt
  README.md
  xmrstak/backend/amd/OclCryptonightR_gen.cpp
  xmrstak/backend/amd/amd_gpu/gpu.cpp
  xmrstak/backend/amd/amd_gpu/opencl/cryptonight.cl
  xmrstak/backend/amd/amd_gpu/opencl/fast_int_math_v2.cl
  xmrstak/backend/amd/config.tpl
  xmrstak/backend/amd/minethd.cpp
  xmrstak/backend/cpu/crypto/CryptonightR_gen.cpp
  xmrstak/backend/cpu/crypto/asm/cnR/CryptonightR_template.S
  xmrstak/backend/cpu/crypto/asm/cnR/CryptonightR_template.asm
  xmrstak/backend/cpu/crypto/asm/cnR/CryptonightR_template.h
  xmrstak/backend/cpu/crypto/asm/cnR/CryptonightR_template.inc
  xmrstak/backend/cpu/crypto/asm/cnR/CryptonightR_template_win.inc
  xmrstak/backend/cpu/crypto/asm/cnR/CryptonightWOW_template.inc
  xmrstak/backend/cpu/crypto/asm/cnR/CryptonightWOW_template_win.inc
  xmrstak/backend/cpu/crypto/asm/cryptonight_v8_double_main_loop_sandybridge_linux.inc
  xmrstak/backend/cpu/crypto/asm/cryptonight_v8_double_main_loop_sandybridge_win64.inc
  xmrstak/backend/cpu/crypto/asm/cryptonight_v8_main_loop.S
  xmrstak/backend/cpu/crypto/asm/cryptonight_v8_main_loop.asm
  xmrstak/backend/cpu/crypto/asm/cryptonight_v8_main_loop_ivybridge_linux.inc
  xmrstak/backend/cpu/crypto/asm/cryptonight_v8_main_loop_ivybridge_win64.inc
  xmrstak/backend/cpu/crypto/asm/cryptonight_v8_main_loop_ryzen_linux.inc
  xmrstak/backend/cpu/crypto/asm/cryptonight_v8_main_loop_ryzen_win64.inc
  xmrstak/backend/cpu/crypto/cn_gpu_avx.cpp
  xmrstak/backend/cpu/crypto/cryptonight.h
  xmrstak/backend/cpu/crypto/cryptonight_aesni.h
  xmrstak/backend/cpu/crypto/cryptonight_common.cpp
  xmrstak/backend/cpu/crypto/variant4_random_math.h
  xmrstak/backend/cpu/minethd.cpp
  xmrstak/backend/cpu/minethd.hpp
  xmrstak/backend/cryptonight.hpp
  xmrstak/backend/nvidia/minethd.cpp
  xmrstak/backend/nvidia/nvcc_code/cryptonight.hpp
  xmrstak/backend/nvidia/nvcc_code/cuda_core.cu
  xmrstak/backend/nvidia/nvcc_code/cuda_extra.cu
  xmrstak/jconf.cpp
  xmrstak/misc/executor.cpp
  xmrstak/pools.tpl
  xmrstak/version.cpp
Labels: documentation

#2296 fix masari
  xmrstak/backend/amd/amd_gpu/gpu.cpp
  xmrstak/backend/amd/amd_gpu/opencl/cryptonight.cl
  xmrstak/backend/amd/autoAdjust.hpp
  xmrstak/backend/amd/minethd.cpp
  xmrstak/backend/miner_work.hpp
  xmrstak/backend/nvidia/minethd.cpp
  xmrstak/backend/nvidia/nvcc_code/cuda_extra.cu
  xmrstak/backend/nvidia/nvcc_code/cuda_keccak.hpp
  xmrstak/cli/cli-miner.cpp
  xmrstak/net/msgstruct.hpp
Labels: bug, currency

#2298 OpenCL: fix windows vega and vii
  xmrstak/backend/amd/amd_gpu/gpu.cpp
  xmrstak/backend/amd/amd_gpu/opencl/cryptonight.cl
Labels: backend amd, bug

#2309 use double hash for cryptonight_r
  xmrstak/backend/cpu/crypto/CryptonightR_gen.cpp
  xmrstak/backend/cpu/crypto/cryptonight.h
  xmrstak/backend/cpu/crypto/cryptonight_aesni.h
  xmrstak/backend/cpu/minethd.cpp
Labels: backend cpu, enhancement

#2310 fix opencl and cuda cryptonight_r caching
  xmrstak/backend/amd/OclCryptonightR_gen.cpp
  xmrstak/backend/amd/OclCryptonightR_gen.hpp
  xmrstak/backend/amd/amd_gpu/gpu.cpp
  xmrstak/backend/nvidia/CudaCryptonightR_gen.cpp
  xmrstak/backend/nvidia/CudaCryptonightR_gen.hpp
  xmrstak/backend/nvidia/nvcc_code/cuda_core.cu
Labels: backend cpu, backend nvidia

#2311 remove wrong documentation
  doc/usage.md
Labels: documentation

#2312 update currency pow table
  xmrstak/jconf.cpp
Labels: currency

#2314 CPU: fix cryptonight_r slowdown
  xmrstak/backend/cpu/crypto/cryptonight_aesni.h
Labels: backend cpu, bug

#2317 fix cn_gpu rounding mode selection
  xmrstak/backend/cpu/crypto/cryptonight_aesni.h
Labels: backend cpu, bug

#2294 fix avx detection
  xmrstak/backend/cpu/cpuType.cpp
Labels: backend cpu, bug

#2316 add cryptonight_v8_double
  README.md
  xmrstak/backend/cpu/minethd.cpp
  xmrstak/backend/cryptonight.hpp
  xmrstak/jconf.cpp
  xmrstak/pools.tpl
Labels: currency

#2326 cryptonight_r without mediaops
  xmrstak/backend/amd/amd_gpu/opencl/cryptonight.cl
  xmrstak/backend/amd/amd_gpu/opencl/wolf-aes.cl
Labels: backend amd

#2327 increase version to 2.10.1
  xmrstak/version.cpp
Labels: documentation

#2328 release 2.10.1
  README.md
  doc/usage.md
  xmrstak/backend/amd/OclCryptonightR_gen.cpp
  xmrstak/backend/amd/OclCryptonightR_gen.hpp
  xmrstak/backend/amd/amd_gpu/gpu.cpp
  xmrstak/backend/amd/amd_gpu/opencl/cryptonight.cl
  xmrstak/backend/amd/amd_gpu/opencl/wolf-aes.cl
  xmrstak/backend/amd/autoAdjust.hpp
  xmrstak/backend/amd/minethd.cpp
  xmrstak/backend/cpu/cpuType.cpp
  xmrstak/backend/cpu/crypto/CryptonightR_gen.cpp
  xmrstak/backend/cpu/crypto/cryptonight.h
  xmrstak/backend/cpu/crypto/cryptonight_aesni.h
  xmrstak/backend/cpu/minethd.cpp
  xmrstak/backend/cryptonight.hpp
  xmrstak/backend/miner_work.hpp
  xmrstak/backend/nvidia/CudaCryptonightR_gen.cpp
  xmrstak/backend/nvidia/CudaCryptonightR_gen.hpp
  xmrstak/backend/nvidia/minethd.cpp
  xmrstak/backend/nvidia/nvcc_code/cuda_core.cu
  xmrstak/backend/nvidia/nvcc_code/cuda_extra.cu
  xmrstak/backend/nvidia/nvcc_code/cuda_keccak.hpp
  xmrstak/cli/cli-miner.cpp
  xmrstak/jconf.cpp
  xmrstak/net/msgstruct.hpp
  xmrstak/pools.tpl
  xmrstak/version.cpp
Labels: documentation

#2335 Repair OSX CUDA searched-path for NVRTC
  CMakeLists.txt
Labels: backend nvidia, bug

#2332 add cli option `amdCacheDir`
  xmrstak/backend/amd/amd_gpu/gpu.cpp
  xmrstak/cli/cli-miner.cpp
  xmrstak/misc/home_dir.hpp
  xmrstak/params.hpp
Labels: backend amd, enhancement

#2345 OpenCL: fix memory leak
  xmrstak/backend/amd/OclCryptonightR_gen.cpp
  xmrstak/backend/amd/OclCryptonightR_gen.hpp
  xmrstak/backend/amd/amd_gpu/gpu.cpp
Labels: backend amd, bug

#2348 increase version to 2.10.2
  xmrstak/version.cpp
Labels: documentation

#2349 release 2.10.2
  CMakeLists.txt
  xmrstak/backend/amd/OclCryptonightR_gen.cpp
  xmrstak/backend/amd/OclCryptonightR_gen.hpp
  xmrstak/backend/amd/amd_gpu/gpu.cpp
  xmrstak/cli/cli-miner.cpp
  xmrstak/misc/home_dir.hpp
  xmrstak/params.hpp
  xmrstak/version.cpp
Labels: documentation

#2363 simple miner startup
  xmrstak/cli/cli-miner.cpp
Labels: feature

#2366 AMD: workaround driver memory leaks
  xmrstak/backend/amd/OclCryptonightR_gen.cpp
  xmrstak/backend/amd/OclCryptonightR_gen.hpp
  xmrstak/backend/amd/amd_gpu/gpu.cpp
  xmrstak/backend/amd/amd_gpu/gpu.hpp
  xmrstak/backend/amd/amd_gpu/opencl/cryptonight_r.rtcl
  xmrstak/backend/amd/amd_gpu/opencl/cryptonight_r_def.rtcl
Labels: backend amd, bug

#2376 use different issue templates
  .github/ISSUE_TEMPLATE.md
  .github/ISSUE_TEMPLATE/compile_bug_report.md
  .github/ISSUE_TEMPLATE/execution_bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/tuning_help.md
Labels: documentation

#2378 update version to 2.10.3
  xmrstak/version.cpp
Labels: documentation

#2380 fix execution issue template
  .github/ISSUE_TEMPLATE/execution_bug_report.md
Labels: bug, documentation

#2385 fix simple start
  xmrstak/cli/cli-miner.cpp
Labels: bug

#2387 avoid hash rate drop during dev pool mining
  xmrstak/backend/amd/minethd.cpp
  xmrstak/backend/cpu/minethd.cpp
  xmrstak/backend/iBackend.hpp
  xmrstak/backend/nvidia/minethd.cpp
Labels: enhancement
