Repository fireice-uk/xmr-stak, pull requests merged in 2019-06, with the labels that each got.

#2443 NVIDIA: optimize cryptonight_gpu
  xmrstak/backend/nvidia/nvcc_code/cuda_aes.hpp
  xmrstak/backend/nvidia/nvcc_code/cuda_core.cu
  xmrstak/backend/nvidia/nvcc_code/cuda_cryptonight_gpu.hpp
  xmrstak/backend/nvidia/nvcc_code/cuda_extra.hpp
  xmrstak/backend/nvidia/nvcc_code/cuda_keccak.hpp
Labels: backend nvidia, refactoring

#2444 dev release option
  CMakeLists.txt
  xmrstak/backend/backendConnector.cpp
Labels: feature

#2447 OpenCL: rocm shuffle
  xmrstak/backend/amd/amd_gpu/gpu.cpp
  xmrstak/backend/amd/amd_gpu/opencl/cryptonight.cl
Labels: backend amd

#2448 increase version to 2.10.5
  xmrstak/version.cpp
Labels: documentation

#2432 Enabling/disabling GPUs from CLI
  xmrstak/backend/amd/autoAdjust.hpp
  xmrstak/backend/nvidia/autoAdjust.hpp
  xmrstak/cli/cli-miner.cpp
  xmrstak/params.hpp
Labels: feature

#2449 release 2.10.5
  CMakeLists.txt
  README.md
  xmrstak/backend/amd/amd_gpu/gpu.cpp
  xmrstak/backend/amd/amd_gpu/opencl/cryptonight.cl
  xmrstak/backend/amd/autoAdjust.hpp
  xmrstak/backend/amd/minethd.cpp
  xmrstak/backend/backendConnector.cpp
  xmrstak/backend/cpu/autoAdjustHwloc.hpp
  xmrstak/backend/cpu/minethd.cpp
  xmrstak/backend/iBackend.hpp
  xmrstak/backend/nvidia/autoAdjust.hpp
  xmrstak/backend/nvidia/minethd.cpp
  xmrstak/backend/nvidia/nvcc_code/cuda_aes.hpp
  xmrstak/backend/nvidia/nvcc_code/cuda_core.cu
  xmrstak/backend/nvidia/nvcc_code/cuda_cryptonight_gpu.hpp
  xmrstak/backend/nvidia/nvcc_code/cuda_extra.hpp
  xmrstak/backend/nvidia/nvcc_code/cuda_keccak.hpp
  xmrstak/cli/cli-miner.cpp
  xmrstak/config.tpl
  xmrstak/jconf.cpp
  xmrstak/misc/executor.cpp
  xmrstak/misc/telemetry.cpp
  xmrstak/misc/telemetry.hpp
  xmrstak/misc/uac.cpp
  xmrstak/params.hpp
  xmrstak/pools.tpl
  xmrstak/version.cpp
Labels: documentation

#2463 doc edits and fixes
  README.md
  doc/FAQ.md
  doc/_img/interleave.png
  doc/_img/stak-yt-cover.jpg
  doc/compile/compile.md
  doc/compile/compile_FreeBSD.md
  doc/compile/compile_Linux.md
  doc/compile/compile_Windows.md
  doc/compile/compile_macOS.md
  doc/troubleshooting.md
  doc/tuning.md
  doc/usage.md
Labels: documentation
