Repository fireice-uk/xmr-stak, pull requests merged in 2019-04, with the labels that each got.

#2391 version increase to 2.10.4
  xmrstak/version.cpp
Labels: documentation

#2392 release 2.10.4
  xmrstak/backend/amd/minethd.cpp
  xmrstak/backend/cpu/minethd.cpp
  xmrstak/backend/iBackend.hpp
  xmrstak/backend/nvidia/minethd.cpp
  xmrstak/backend/nvidia/nvcc_code/cuda_cryptonight_r.curt
  xmrstak/cli/cli-miner.cpp
  xmrstak/version.cpp
Labels: documentation

#2393 concurrent hash rate calculation
  xmrstak/misc/telemetry.cpp
  xmrstak/misc/telemetry.hpp
Labels: refactoring

#2409 fix benchmark mode
  xmrstak/cli/cli-miner.cpp
Labels: backend amd, backend cpu, backend nvidia, bug

#2415 --log CLI parameter
  xmrstak/cli/cli-miner.cpp
  xmrstak/config.tpl
  xmrstak/jconf.cpp
  xmrstak/params.hpp
Labels: enhancement
