Repository fireice-uk/xmr-stak, pull requests merged in 2019-07, with the labels that each got.

#2467 NVIDIA: fix cryptonight_v8 and derived pows
  xmrstak/backend/nvidia/nvcc_code/cuda_core.cu
Labels: backend nvidia, bug

#2468 NVIDIA: releax 'threads' config
  xmrstak/backend/nvidia/nvcc_code/cryptonight.hpp
  xmrstak/backend/nvidia/nvcc_code/cuda_core.cu
  xmrstak/backend/nvidia/nvcc_code/cuda_extra.cu
Labels: backend nvidia, enhancement

#2482 fix AMD driver 19.7.X bug
  xmrstak/backend/amd/amd_gpu/opencl/cryptonight.cl
  xmrstak/backend/amd/amd_gpu/opencl/wolf-skein.cl
Labels: backend amd, bug

#2483 increase version to 2.10.6
  xmrstak/version.cpp
Labels: documentation

#2485 release 2.10.6
  README.md
  doc/FAQ.md
  doc/_img/interleave.png
  doc/_img/stak-yt-cover.jpg
  doc/compile/compile.md
  doc/compile/compile_FreeBSD.md
  doc/compile/compile_Linux.md
  doc/compile/compile_Windows.md
  doc/compile/compile_macOS.md
  doc/troubleshooting.md
  doc/tuning.md
  doc/usage.md
  xmrstak/backend/amd/amd_gpu/opencl/cryptonight.cl
  xmrstak/backend/amd/amd_gpu/opencl/wolf-skein.cl
  xmrstak/backend/nvidia/nvcc_code/cryptonight.hpp
  xmrstak/backend/nvidia/nvcc_code/cuda_core.cu
  xmrstak/backend/nvidia/nvcc_code/cuda_extra.cu
  xmrstak/version.cpp
Labels: documentation

#2477 Make explicit the architecture of the project at beginning
  README.md
Labels: documentation

#2495 NVIDIA: fix broken phase 3
  xmrstak/backend/nvidia/nvcc_code/cuda_core.cu
Labels: backend nvidia, bug

#2494 AMD: optimize VEGA auto suggestion
  xmrstak/backend/amd/autoAdjust.hpp
Labels: backend amd, enhancement

#2497 remove unsupported currencies
  README.md
  xmrstak/jconf.cpp
Labels: currency

#2496 set version to 2.10.7
  xmrstak/version.cpp
Labels: documentation

#2458 Updated the broken links in usage.md
  doc/usage.md
Labels: documentation

#2498 release 2.10.7
  README.md
  doc/usage.md
  xmrstak/backend/amd/autoAdjust.hpp
  xmrstak/backend/nvidia/nvcc_code/cuda_core.cu
  xmrstak/jconf.cpp
  xmrstak/version.cpp
Labels: documentation
